#!/usr/bin/env bash
# Build the unified documentation site with Zensical.
#
# The site combines two generated API references that must be produced before
# Zensical runs:
#   1. The Python API reference is generated at build time by mkdocstrings
#      (no pre-step needed).
#   2. The frontend (TypeScript) API reference is generated by TypeDoc into
#      docs/frontend/api/ (a git-ignored build artifact), so it must be
#      regenerated here first or the nav would reference missing pages.
#
# Zensical does not yet implement mkdocs-literate-nav's directory-tree
# inference, so after TypeDoc runs, script/generate_docs_config.py expands the
# `frontend/api/` nav entry in mkdocs.yml into an explicit tree and writes the
# git-ignored mkdocs.generated.yml, which Zensical then builds from.
#
# Usage:
#   script/build_docs.sh [--serve] [-- <extra zensical args>]
#
#   --serve   Run `zensical serve` (live reload) instead of
#             `zensical build --strict`.
#
# Requires: Node + npm on PATH and the uv `docs` dependency group
# (uv sync --group docs). Frontend deps are installed automatically if the
# TypeDoc binary is missing (e.g. a fresh checkout that never ran `npm ci`).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

SERVE=0
EXTRA_ARGS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --serve) SERVE=1; shift ;;
    --) shift; EXTRA_ARGS+=("$@"); break ;;
    *) EXTRA_ARGS+=("$1"); shift ;;
  esac
done

# TypeDoc lives in frontend/node_modules; on a fresh checkout that never ran
# `npm ci`/`npm install` the binary is absent, which would otherwise fail with
# a cryptic "typedoc: not found". Bootstrap the frontend deps in that case so
# the script works out of the box. (No-op when deps are already present.)
if [[ ! -x "$REPO_ROOT/frontend/node_modules/.bin/typedoc" ]]; then
  if ! command -v npm >/dev/null 2>&1; then
    echo "error: npm not found on PATH. Install Node.js 22+ to build the docs." >&2
    exit 1
  fi
  echo "==> TypeDoc not found; installing frontend dependencies (npm ci)"
  ( cd "$REPO_ROOT/frontend" && npm ci )
fi

echo "==> Generating frontend (TypeScript) API reference with TypeDoc"
( cd "$REPO_ROOT/frontend" && npm run docs:api )

echo "==> Expanding nav into mkdocs.generated.yml"
( cd "$REPO_ROOT" && uv run --group docs python script/generate_docs_config.py )

if [[ $SERVE -eq 1 ]]; then
  echo "==> Serving docs (live reload) at http://127.0.0.1:8000"
  ( cd "$REPO_ROOT" && uv run --group docs zensical serve -f mkdocs.generated.yml "${EXTRA_ARGS[@]}" )
else
  echo "==> Building static site (strict) into site/"
  ( cd "$REPO_ROOT" && uv run --group docs zensical build --strict -f mkdocs.generated.yml "${EXTRA_ARGS[@]}" )
fi
