#!/usr/bin/env bash
# Build the unified documentation site.
#
# The site combines two generated API references that must be produced before
# MkDocs runs:
#   1. The Python API reference is generated at MkDocs build time by
#      mkdocstrings (no pre-step needed).
#   2. The frontend (TypeScript) API reference is generated by TypeDoc into
#      docs/frontend/api/ (a git-ignored build artifact), so it must be
#      regenerated here first or the MkDocs nav would reference missing pages.
#
# Usage:
#   script/build_docs.sh [--serve] [-- <extra mkdocs args>]
#
#   --serve   Run `mkdocs serve` (live reload) instead of `mkdocs build --strict`.
#
# Requires: Node + npm on PATH and the uv `docs` dependency group
# (uv sync --group docs). Frontend deps are installed automatically if the
# TypeDoc binary is missing (e.g. a fresh checkout that never ran `npm ci`).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

SERVE=0
EXTRA_ARGS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --serve) SERVE=1; shift ;;
    --) shift; EXTRA_ARGS+=("$@"); break ;;
    *) EXTRA_ARGS+=("$1"); shift ;;
  esac
done

# TypeDoc lives in frontend/node_modules; on a fresh checkout that never ran
# `npm ci`/`npm install` the binary is absent, which would otherwise fail with
# a cryptic "typedoc: not found". Bootstrap the frontend deps in that case so
# the script works out of the box. (No-op when deps are already present.)
if [[ ! -x "$REPO_ROOT/frontend/node_modules/.bin/typedoc" ]]; then
  if ! command -v npm >/dev/null 2>&1; then
    echo "error: npm not found on PATH. Install Node.js 22+ to build the docs." >&2
    exit 1
  fi
  echo "==> TypeDoc not found; installing frontend dependencies (npm ci)"
  ( cd "$REPO_ROOT/frontend" && npm ci )
fi

echo "==> Generating frontend (TypeScript) API reference with TypeDoc"
( cd "$REPO_ROOT/frontend" && npm run docs:api )

# Silence Material for MkDocs' unrelated MkDocs-2.0 promo banner in CI logs.
export DISABLE_MKDOCS_2_WARNING=true

if [[ $SERVE -eq 1 ]]; then
  echo "==> Serving docs (live reload) at http://127.0.0.1:8000"
  ( cd "$REPO_ROOT" && uv run --group docs mkdocs serve "${EXTRA_ARGS[@]}" )
else
  echo "==> Building static site (strict) into site/"
  ( cd "$REPO_ROOT" && uv run --group docs mkdocs build --strict "${EXTRA_ARGS[@]}" )
fi
